### ISSUE TITLE
--version fails if platex is not installed

### ISSUE THREAD

**Issue by septatrix** [python/docsbuild-scripts#102]
`platex` is not required if one wants to e.g. only build the english documentation. It would therefore make sense to catch such errors and list the program as not installed.

```python
Traceback (most recent call last):
  File "./build_docs.py", line 802, in <module>
    main()
  File "./build_docs.py", line 741, in main
    version_info()
  File "./build_docs.py", line 626, in version_info
    subprocess.check_output(["platex", "--version"], universal_newlines=True), n=3
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'platex'
```

**Comment by JulienPalard** [comment]
Fixed in 317333621cb4f067cc02b1bda3136fb16c74f189, thanks for reporting :)
