### ISSUE TITLE
Failure affecting ja/3.13: "Badly handled exception, human, please help"

### ISSUE THREAD

**Issue by hugovk** [python/docsbuild-scripts#192]
https://docs.python.org/ja/3.13/ last built on Aug 18, 2024 (13:56 UTC) and is now failing. It's not  very clear what the problem is, but looks like Latexmk or LuaHBTeX:

```
2024-08-26 15:02:41,201 INFO ja/3.13: Running.
2024-08-26 15:02:41,202 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython show-ref -s origin/3.13'
2024-08-26 15:02:41,207 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 3b7e5b640f4d5e70c7ac88375f729c1b2ce833c0 --'
2024-08-26 15:02:41,237 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython clean -dfqx'
2024-08-26 15:02:41,440 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES fetch'
2024-08-26 15:02:41,988 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES branch -r'
2024-08-26 15:02:41,991 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES show-ref -s origin/3.11'
2024-08-26 15:02:41,994 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES reset --hard bf8eab143222700c4e9c281ea846fa38de1b941c --'
2024-08-26 15:02:42,538 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES clean -dfqx'
2024-08-26 15:02:42,697 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython rev-parse HEAD'
2024-08-26 15:02:42,700 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES rev-parse HEAD'
2024-08-26 15:02:42,702 INFO ja/3.13: Should rebuild: new translations (from 17f81eab4fc00e513dd1ca7311c0dea267f32a2e to bf8eab143222700c4e9c281ea846fa38de1b941c)
2024-08-26 15:02:42,703 DEBUG ja/3.13: Run: '/srv/docsbuild/venv/bin/python -m venv /srv/docsbuild/venv-3.13'
2024-08-26 15:02:44,885 DEBUG ja/3.13: Run: '/srv/docsbuild/venv-3.13/bin/python -m pip install --upgrade python-docs-theme jieba -rrequirements.txt'
2024-08-26 15:02:45,979 DEBUG ja/3.13: Run: '/srv/docsbuild/venv-3.13/bin/python -m pip freeze --all'
2024-08-26 15:02:46,433 INFO ja/3.13: Build start.
2024-08-26 15:02:46,717 INFO ja/3.13: Running make autobuild-dev
2024-08-26 15:02:46,718 DEBUG ja/3.13: Run: "sed -i 's/ *-A switchers=1//' /srv/docsbuild/cpython/Doc/Makefile"
2024-08-26 15:02:46,725 DEBUG ja/3.13: Run: "make -C /srv/docsbuild/cpython/Doc PYTHON=/srv/docsbuild/venv-3.13/bin/python SPHINXBUILD=/srv/docsbuild/venv-3.13/bin/sphinx-build BLURB=/srv/docsbuild/venv-3.13/bin/blurb VENVDIR=/srv/docsbuild/venv-3.13 'SPHINXOPTS=-D latex_engine=lualatex -D latex_elements.inputenc= -D latex_elements.fontenc= -D latex_docclass.manual=ltjsbook -D latex_docclass.howto=ltjsarticle -D latex_elements.polyglossia= -D latex_elements.fontpkg= -D latex_elements.preamble=\\\\usepackage[noto-otf]{luatexja-preset}\\\\usepackage{newunicodechar}\\\\newunicodechar{^^^^212a}{K}\\\\makeatletter\\\\titleformat{\\\\subsubsection}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubsubsection}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\paragraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\theparagraph}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\subparagraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubparagraph}{0.5em}{\\\\py@TitleColor}\\\\makeatother\\\\setlength{\\\\footskip}{16.4pt} -q -D locale_dirs=/srv/docsbuild/3.13/locale -D language=ja -D gettext_compact=0' SPHINXERRORHANDLING= autobuild-dev"
2024-08-26 15:07:02,130 INFO: Another builder is running... dying...
2024-08-26 15:57:09,406 ERROR ja/3.13: Run: "make -C /srv/docsbuild/cpython/Doc PYTHON=/srv/docsbuild/venv-3.13/bin/python SPHINXBUILD=/srv/docsbuild/venv-3.13/bin/sphinx-build BLURB=/srv/docsbuild/venv-3.13/bin/blurb VENVDIR=/srv/docsbuild/venv-3.13 'SPHINXOPTS=-D latex_engine=lualatex -D latex_elements.inputenc= -D latex_elements.fontenc= -D latex_docclass.manual=ltjsbook -D latex_docclass.howto=ltjsarticle -D latex_elements.polyglossia= -D latex_elements.fontpkg= -D latex_elements.preamble=\\\\usepackage[noto-otf]{luatexja-preset}\\\\usepackage{newunicodechar}\\\\newunicodechar{^^^^212a}{K}\\\\makeatletter\\\\titleformat{\\\\subsubsection}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubsubsection}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\paragraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\theparagraph}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\subparagraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubparagraph}{0.5em}{\\\\py@TitleColor}\\\\makeatother\\\\setlength{\\\\footskip}{16.4pt} -q -D locale_dirs=/srv/docsbuild/3.13/locale -D language=ja -D gettext_compact=0' SPHINXERRORHANDLING= autobuild-dev" KO:
    Latexmk: Run number 1 of rule 'pdflatex'
    This is LuaHBTeX, Version 1.17.0 (TeX Live 2023/Debian) 
     restricted system commands enabled.
    Latexmk: Getting log file 'reference.log'
    Latexmk: Run number 1 of rule 'makeindex reference.idx'
    Latexmk: Run number 2 of rule 'pdflatex'
    This is LuaHBTeX, Version 1.17.0 (TeX Live 2023/Debian) 
     restricted system commands enabled.
    Latexmk: Getting log file 'reference.log'
    Latexmk: Run number 3 of rule 'pdflatex'
    This is LuaHBTeX, Version 1.17.0 (TeX Live 2023/Debian) 
     restricted system commands enabled.
    Latexmk: Getting log file 'reference.log'

    make[2]: Leaving directory '/srv/docsbuild/cpython/Doc/build/latex'
    make[1]: *** [Makefile:226: dist] Error 2
    make[1]: Leaving directory '/srv/docsbuild/cpython/Doc'
    make: *** [Makefile:289: autobuild-dev] Error 2
    make: Leaving directory '/srv/docsbuild/cpython/Doc'

2024-08-26 15:57:09,582 ERROR ja/3.13: Badly handled exception, human, please help.
Traceback (most recent call last):
  File "/srv/docsbuild/scripts/build_docs.py", line 655, in run
    self.build()
  File "/srv/docsbuild/scripts/build_docs.py", line 762, in build
    run(
  File "/srv/docsbuild/scripts/build_docs.py", line 247, in run
    result.check_returncode()
  File "/usr/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['make', '-C', '/srv/docsbuild/cpython/Doc', 'PYTHON=/srv/docsbuild/venv-3.13/bin/python', 'SPHINXBUILD=/srv/docsbuild/venv-3.13/bin/sphinx-build', 'BLURB=/srv/docsbuild/venv-3.13/bin/blurb', 'VENVDIR=/srv/docsbuild/venv-3.13', 'SPHINXOPTS=-D latex_engine=lualatex -D latex_elements.inputenc= -D latex_elements.fontenc= -D latex_docclass.manual=ltjsbook -D latex_docclass.howto=ltjsarticle -D latex_elements.polyglossia= -D latex_elements.fontpkg= -D latex_elements.preamble=\\\\usepackage[noto-otf]{luatexja-preset}\\\\usepackage{newunicodechar}\\\\newunicodechar{^^^^212a}{K}\\\\makeatletter\\\\titleformat{\\\\subsubsection}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubsubsection}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\paragraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\theparagraph}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\subparagraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubparagraph}{0.5em}{\\\\py@TitleColor}\\\\makeatother\\\\setlength{\\\\footskip}{16.4pt} -q -D locale_dirs=/srv/docsbuild/3.13/locale -D language=ja -D gettext_compact=0', 'SPHINXERRORHANDLING=', 'autobuild-dev']' returned non-zero exit status 2.
2024-08-26 15:57:09,695 DEBUG ja/3.13: Resetting dropped connection: sentry.io
```

Last successful build:

<details>
<summary>Details</summary>

```
2024-08-18 13:56:17,877 INFO ja/3.13: Running.
2024-08-18 13:56:17,877 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython show-ref -s origin/3.13'
2024-08-18 13:56:17,880 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 6001deacb73e10e6f4b6fc16286cfda2babeb59e --'
2024-08-18 13:56:17,907 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython clean -dfqx'
2024-08-18 13:56:18,090 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES fetch'
2024-08-18 13:56:18,580 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES branch -r'
2024-08-18 13:56:18,583 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES show-ref -s origin/3.11'
2024-08-18 13:56:18,588 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES reset --hard 17f81eab4fc00e513dd1ca7311c0dea267f32a2e --'
2024-08-18 13:56:19,004 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES clean -dfqx'
2024-08-18 13:56:19,151 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython rev-parse HEAD'
2024-08-18 13:56:19,154 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES rev-parse HEAD'
2024-08-18 13:56:19,157 INFO ja/3.13: Should rebuild: new translations (from 4098cdb388152c9d21ed5a6603aebe756c6fe832 to 17f81eab4fc00e513dd1ca7311c0dea267f32a2e)
2024-08-18 13:56:19,158 DEBUG ja/3.13: Run: '/srv/docsbuild/venv/bin/python -m venv /srv/docsbuild/venv-3.13'
2024-08-18 13:56:21,505 DEBUG ja/3.13: Run: '/srv/docsbuild/venv-3.13/bin/python -m pip install --upgrade python-docs-theme jieba -rrequirements.txt'
2024-08-18 13:56:22,762 DEBUG ja/3.13: Run: '/srv/docsbuild/venv-3.13/bin/python -m pip freeze --all'
2024-08-18 13:56:23,198 INFO ja/3.13: Build start.
2024-08-18 13:56:23,475 INFO ja/3.13: Running make autobuild-dev
2024-08-18 13:56:23,476 DEBUG ja/3.13: Run: "sed -i 's/ *-A switchers=1//' /srv/docsbuild/cpython/Doc/Makefile"
2024-08-18 13:56:23,483 DEBUG ja/3.13: Run: "make -C /srv/docsbuild/cpython/Doc PYTHON=/srv/docsbuild/venv-3.13/bin/python SPHINXBUILD=/srv/docsbuild/venv-3.13/bin/sphinx-build BLURB=/srv/docsbuild/venv-3.13/bin/blurb VENVDIR=/srv/docsbuild/venv-3.13 'SPHINXOPTS=-D latex_engine=lualatex -D latex_elements.inputenc= -D latex_elements.fontenc= -D latex_docclass.manual=ltjsbook -D latex_docclass.howto=ltjsarticle -D latex_elements.polyglossia= -D latex_elements.fontpkg= -D latex_elements.preamble=\\\\usepackage[noto-otf]{luatexja-preset}\\\\usepackage{newunicodechar}\\\\newunicodechar{^^^^212a}{K}\\\\makeatletter\\\\titleformat{\\\\subsubsection}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubsubsection}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\paragraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\theparagraph}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\subparagraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubparagraph}{0.5em}{\\\\py@TitleColor}\\\\makeatother\\\\setlength{\\\\footskip}{16.4pt} -q -D locale_dirs=/srv/docsbuild/3.13/locale -D language=ja -D gettext_compact=0' SPHINXERRORHANDLING= autobuild-dev"
2024-08-18 14:07:01,882 INFO: Another builder is running... dying...
2024-08-18 15:07:02,197 INFO: Another builder is running... dying...
2024-08-18 15:50:28,753 DEBUG ja/3.13: Run: 'mkdir -p /var/log/docsbuild'
2024-08-18 15:50:28,757 DEBUG ja/3.13: Run: 'chgrp -R docs /var/log/docsbuild'
2024-08-18 15:50:29,382 INFO ja/3.13: Build done.
2024-08-18 15:50:29,382 INFO ja/3.13: Publishing start.
...
```

</details>

https://docs.python.org/ja/3.12/ and https://docs.python.org/ja/3.14/ are both building fine:

<details>
<summary>Details</summary>

```
2024-08-26 01:54:08,142 INFO ja/3.14: Running.
2024-08-26 01:54:08,142 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/cpython show-ref -s origin/main'
2024-08-26 01:54:08,147 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 625d0705b9ab348f85853ed73b796763b70154a5 --'
2024-08-26 01:54:08,188 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/cpython clean -dfqx'
2024-08-26 01:54:08,398 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/3.14/locale/ja/LC_MESSAGES fetch'
2024-08-26 01:54:08,871 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/3.14/locale/ja/LC_MESSAGES branch -r'
2024-08-26 01:54:08,874 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/3.14/locale/ja/LC_MESSAGES show-ref -s origin/3.11'
2024-08-26 01:54:08,878 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/3.14/locale/ja/LC_MESSAGES reset --hard bf8eab143222700c4e9c281ea846fa38de1b941c --'
2024-08-26 01:54:09,447 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/3.14/locale/ja/LC_MESSAGES clean -dfqx'
2024-08-26 01:54:09,576 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/cpython rev-parse HEAD'
2024-08-26 01:54:09,580 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/3.14/locale/ja/LC_MESSAGES rev-parse HEAD'
2024-08-26 01:54:09,583 INFO ja/3.14: Should rebuild: new translations (from 70e179a119741303fe6033146cd2f213e025a8e8 to bf8eab143222700c4e9c281ea846fa38de1b941c)
2024-08-26 01:54:09,584 DEBUG ja/3.14: Run: '/srv/docsbuild/venv/bin/python -m venv /srv/docsbuild/venv-3.14'
2024-08-26 01:54:12,086 DEBUG ja/3.14: Run: '/srv/docsbuild/venv-3.14/bin/python -m pip install --upgrade python-docs-theme jieba -rrequirements.txt'
2024-08-26 01:54:13,490 DEBUG ja/3.14: Run: '/srv/docsbuild/venv-3.14/bin/python -m pip freeze --all'
2024-08-26 01:54:14,061 INFO ja/3.14: Build start.
2024-08-26 01:54:14,327 INFO ja/3.14: Running make autobuild-dev
2024-08-26 01:54:14,328 DEBUG ja/3.14: Run: "sed -i 's/ *-A switchers=1//' /srv/docsbuild/cpython/Doc/Makefile"
2024-08-26 01:54:14,335 DEBUG ja/3.14: Run: "make -C /srv/docsbuild/cpython/Doc PYTHON=/srv/docsbuild/venv-3.14/bin/python SPHINXBUILD=/srv/docsbuild/venv-3.14/bin/sphinx-build BLURB=/srv/docsbuild/venv-3.14/bin/blurb VENVDIR=/srv/docsbuild/venv-3.14 'SPHINXOPTS=-D latex_engine=lualatex -D latex_elements.inputenc= -D latex_elements.fontenc= -D latex_docclass.manual=ltjsbook -D latex_docclass.howto=ltjsarticle -D latex_elements.polyglossia= -D latex_elements.fontpkg= -D latex_elements.preamble=\\\\usepackage[noto-otf]{luatexja-preset}\\\\usepackage{newunicodechar}\\\\newunicodechar{^^^^212a}{K}\\\\makeatletter\\\\titleformat{\\\\subsubsection}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubsubsection}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\paragraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\theparagraph}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\subparagraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubparagraph}{0.5em}{\\\\py@TitleColor}\\\\makeatother\\\\setlength{\\\\footskip}{16.4pt} -q -D locale_dirs=/srv/docsbuild/3.14/locale -D language=ja -D gettext_compact=0' SPHINXERRORHANDLING= autobuild-dev"
2024-08-26 02:07:01,561 INFO: Another builder is running... dying...
2024-08-26 03:07:01,989 INFO: Another builder is running... dying...
2024-08-26 03:09:34,834 DEBUG ja/3.14: Run: 'mkdir -p /var/log/docsbuild'
2024-08-26 03:09:34,837 DEBUG ja/3.14: Run: 'chgrp -R docs /var/log/docsbuild'
2024-08-26 03:09:36,471 INFO ja/3.14: Build done.
2024-08-26 03:09:36,471 INFO ja/3.14: Publishing start.
...
```

</details>

**Comment by hugovk** [comment]
I don't know what's changed, but this is now working:

> 最終更新: Sep 03, 2024 (07:16 UTC)

```
2024-09-03 07:16:18,228 INFO ja/3.13: Running.
2024-09-03 07:16:18,228 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython show-ref -s origin/3.13'
2024-09-03 07:16:18,232 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard b8ef767ba52305a38e3d4ad850439cceec75a3b8 --'
2024-09-03 07:16:18,268 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython clean -dfqx'
2024-09-03 07:16:18,528 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES fetch'
2024-09-03 07:16:18,962 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES branch -r'
2024-09-03 07:16:18,965 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES show-ref -s origin/3.11'
2024-09-03 07:16:18,971 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES reset --hard fc7100f4a364cd5cfff9c3837794cfe0ce05a7fb --'
2024-09-03 07:16:19,558 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES clean -dfqx'
2024-09-03 07:16:19,758 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython rev-parse HEAD'
2024-09-03 07:16:19,762 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/3.13/locale/ja/LC_MESSAGES rev-parse HEAD'
2024-09-03 07:16:19,765 INFO ja/3.13: Should rebuild: new translations (from fb1461a75c13bfd7df62391b0fd7160a62198db1 to fc7100f4a364cd5cfff9c3837794cfe0ce05a7fb)
2024-09-03 07:16:19,766 DEBUG ja/3.13: Run: '/srv/docsbuild/venv/bin/python -m venv /srv/docsbuild/venv-3.13'
2024-09-03 07:16:23,151 DEBUG ja/3.13: Run: '/srv/docsbuild/venv-3.13/bin/python -m pip install --upgrade python-docs-theme jieba -rrequirements.txt'
2024-09-03 07:16:24,391 DEBUG ja/3.13: Run: '/srv/docsbuild/venv-3.13/bin/python -m pip freeze --all'
2024-09-03 07:16:24,875 INFO ja/3.13: Build start.
2024-09-03 07:16:25,223 INFO ja/3.13: Running make autobuild-dev
2024-09-03 07:16:25,223 DEBUG ja/3.13: Run: "sed -i 's/ *-A switchers=1//' /srv/docsbuild/cpython/Doc/Makefile"
2024-09-03 07:16:25,230 DEBUG ja/3.13: Run: "make -C /srv/docsbuild/cpython/Doc PYTHON=/srv/docsbuild/venv-3.13/bin/python SPHINXBUILD=/srv/docsbuild/venv-3.13/bin/sphinx-build BLURB=/srv/docsbuild/venv-3.13/bin/blurb VENVDIR=/srv/docsbuild/venv-3.13 'SPHINXOPTS=-D latex_engine=lualatex -D latex_elements.inputenc= -D latex_elements.fontenc= -D latex_docclass.manual=ltjsbook -D latex_docclass.howto=ltjsarticle -D latex_elements.polyglossia= -D latex_elements.fontpkg= -D latex_elements.preamble=\\\\usepackage[noto-otf]{luatexja-preset}\\\\usepackage{newunicodechar}\\\\newunicodechar{^^^^212a}{K}\\\\makeatletter\\\\titleformat{\\\\subsubsection}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubsubsection}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\paragraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\theparagraph}{0.5em}{\\\\py@TitleColor}\\\\titleformat{\\\\subparagraph}{\\\\normalsize\\\\py@HeaderFamily}{\\\\py@TitleColor\\\\thesubparagraph}{0.5em}{\\\\py@TitleColor}\\\\makeatother\\\\setlength{\\\\footskip}{16.4pt} -q -D locale_dirs=/srv/docsbuild/3.13/locale -D language=ja -D gettext_compact=0' SPHINXERRORHANDLING= autobuild-dev"
2024-09-03 08:07:02,259 INFO: Another builder is running... dying...
2024-09-03 08:39:24,067 DEBUG ja/3.13: Run: 'mkdir -p /var/log/docsbuild'
2024-09-03 08:39:24,072 DEBUG ja/3.13: Run: 'chgrp -R docs /var/log/docsbuild'
2024-09-03 08:39:25,858 INFO ja/3.13: Build done.
2024-09-03 08:39:25,859 INFO ja/3.13: Publishing start.
2024-09-03 08:39:25,859 DEBUG ja/3.13: Run: 'chgrp -R docs /srv/docs.python.org/ja'
2024-09-03 08:39:26,292 DEBUG ja/3.13: Run: 'chgrp -R docs /srv/docs.python.org/ja/3.13'
2024-09-03 08:39:28,304 INFO ja/3.13: Copying HTML files to /srv/docs.python.org/ja/3.13
2024-09-03 08:39:28,305 DEBUG ja/3.13: Run: 'chown -R :docs /srv/docsbuild/cpython/Doc/build/html'
2024-09-03 08:39:28,313 DEBUG ja/3.13: Run: 'chmod -R o+r /srv/docsbuild/cpython/Doc/build/html'
2024-09-03 08:39:28,319 DEBUG ja/3.13: Run: "find /srv/docsbuild/cpython/Doc/build/html -type d -exec chmod o+x '{}' ';'"
2024-09-03 08:39:28,366 DEBUG ja/3.13: Run: "rsync -a --delete-delay --filter 'P archives/' /srv/docsbuild/cpython/Doc/build/html/ /srv/docs.python.org/ja/3.13"
2024-09-03 08:39:28,896 DEBUG ja/3.13: Copying dist files.
2024-09-03 08:39:28,896 DEBUG ja/3.13: Run: 'chown -R :docs /srv/docsbuild/cpython/Doc/dist'
2024-09-03 08:39:28,898 DEBUG ja/3.13: Run: 'chmod -R o+r /srv/docsbuild/cpython/Doc/dist'
2024-09-03 08:39:28,900 DEBUG ja/3.13: Run: 'mkdir -m o+rx -p /srv/docs.python.org/ja/3.13/archives'
2024-09-03 08:39:28,902 DEBUG ja/3.13: Run: 'chown :docs /srv/docs.python.org/ja/3.13/archives'
2024-09-03 08:39:28,904 DEBUG ja/3.13: Run: 'cp -a /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-pdf-a4.tar.bz2 /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-texinfo.tar.bz2 /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-pdf-a4.zip /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-texinfo.zip /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-text.tar.bz2 /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-text.zip /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-pdf-letter.tar.bz2 /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-html.zip /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-pdf-letter.zip /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs.epub /srv/docsbuild/cpython/Doc/dist/python-3.13.0rc1-docs-html.tar.bz2 /srv/docs.python.org/ja/3.13/archives'
2024-09-03 08:39:29,423 INFO ja/3.13: 786 files changed
2024-09-03 08:39:29,423 DEBUG ja/3.13: Run: 'find -L /srv/docs.python.org -samefile /srv/docs.python.org/ja/3.13'
2024-09-03 08:39:43,039 DEBUG ja/3.13: Purging https://docs.python.org/ja/3.13/ from CDN
2024-09-03 08:39:43,044 DEBUG ja/3.13: Starting new HTTPS connection (1): docs.python.org:443
2024-09-03 08:39:43,096 DEBUG ja/3.13: https://docs.python.org:443 "PURGE /ja/3.13/ HTTP/1.1" 200 52
2024-09-03 08:39:43,098 DEBUG ja/3.13: Purging https://docs.python.org/ja/3.13/.buildinfo from CDN
2024-09-03 08:39:43,099 DEBUG ja/3.13: Starting new HTTPS connection (1): docs.python.org:443
...
```

Last failure was:
```
2024-08-29 12:50:53,154 ERROR ja/3.13: Badly handled exception, human, please help.
```
